# Generated by Django 6.1 on 2026-09-04 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('election_type', models.CharField(choices=[('PORTE_PAROLE', 'Porte-parole'), ('PREFAC', 'Président facultaire'), ('CP', 'Chef de promotion')], max_length=30)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('faculte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='academique.faculte')),
                ('filieres', models.ManyToManyField(blank=True, related_name='elections', to='academique.filiere')),
                ('promotion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='elections', to='academique.promotion')),
            ],
        ),
    ]
