# Generated by Django 6.1 on 2026-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='nom',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.UniqueConstraint(fields=('nom', 'departement'), name='unique_promotion_per_departement'),
        ),
    ]
